### ISSUE TITLE
connect to cassandra with optional username/password

### ISSUE THREAD

**Issue by WrathOfChris** [WrathOfChris/cyanite-utils#5]
example yaml format

```
store:
  cluster:
    - "host01-1"
    - "host01-2"
  keyspace: 'metric'
  username: "graphite"
  password: "graphite"
```
